### ISSUE TITLE
Different codes between npm and git 

### ISSUE THREAD

**Issue by mitwave** [NotNinja/node-blinkt#1]
Hi.
If I install your module via npm command, there are many typo in your code and required rpio.
However, on your git site, there are different code and dependencies in package.json...

Would you update for npm?

Mitwave

**Comment by airmrcr** [comment]
@mitwave I have released 0.0.2 to contain the latest changes that were in `master`. The library still isn't in a complete state and I've found it doesn't work quite as well as the Python library provided by Pimoroni, however, I believe it can with more work. The transitioning just doesn't appear to be as fluid and I can't work out why and have little time to do so. This is a pet project but I'll hopefully be able to work it out eventually, given time.

Let me know how you get on with it.
